steps:
  # Build the custom builder image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/angular-app-builder",
        "-f",
        "Dockerfile.builder",
        ".",
      ]

  # Run unit tests with the custom builder image
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "gcr.io/$PROJECT_ID/angular-app-builder"]

  # Build the Angular app
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # Deploy the app to a web server (replace [YOUR_BUCKET_NAME] with the name of your GCS bucket)
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "cp", "-r", "dist/*", "gs://ichair-app/"]
